from pydantic_settings import BaseSettings, SettingsConfigDict


class ComposerSettings(BaseSettings):
    """
    Composer settings that can be extended with env support if needed.
    """

    composers: list[str] = [
        "Alex North",
        "Alexandre Desplat",
        "Angela Morley",
        "Arthur B. Rubinstein",
        "Basil Poledouris",
        "Bernard Herrmann",
        "Bill Conti",
        "Christopher Young",
        "Dave Grusin",
        "David Amram",
        "David Arnold",
        "David Raksin",
        "David Shire",
        "Debbie Wiseman",
        "Dimitri Tiomkin",
        "Elmer Bernstein",
        "Elliot Goldenthal",
        "Ennio Morricone",
        "Eric Demarsan",
        "Francis Lai",
        "François de Roubaix",
        "Fred Karlin",
        "Fred Myrow",
        "Gabriel Yared",
        "Gato Barbieri",
        "Georges Delerue",
        "Hans Zimmer",
        "Harry Robinson",
        "Henry Mancini",
        "Howard Blake",
        "Howard Shore",
        "James Horner",
        "James Newton Howard",
        "Jerry Fielding",
        "Jerry Goldsmith",
        "John Addison",
        "John Barry",
        "John Williams",
        "Johnny Mandel",
        "Joe Hisaishi",
        "Krzysztof Komeda",
        "Lalo Schifrin",
        "Laurie Johnson",
        "Leonard Rosenman",
        "Lennie Niehaus",
        "Marvin Hamlisch",
        "Max Steiner",
        "Michael Gore",
        "Michael Nyman",
        "Michael Small",
        "Michel Colombier",
        "Michel Legrand",
        "Michel Magne",
        "Miklos Rozsa",
        "Oliver Nelson",
        "Patrick Doyle",
        "Philippe Sarde",
        "Pino Donaggio",
        "Richard Band",
        "Richard Rodney Bennett",
        "Roy Budd",
        "Ryuichi Sakamoto",
        "Stephen Sondheim",
        "Trevor Jones",
        "Vladimir Cosma",
        "Wojciech Kilar",
    ]

    model_config = SettingsConfigDict(env_prefix="COMPOSER_", case_sensitive=False)
