name: Run main.py

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  run-main:
    runs-on: ubuntu-latest

    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Show Python version
        run: python --version

      - name: Install dependencies with PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          pdm install --prod

      - name: Run main.py script
        run: python src/hollywood_pub_sub/main.py --api_key "$TMDB_API_KEY" --max_movies_per_composer 10 --winning_threshold 5

