name: Run Main Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-main:
    runs-on: ubuntu-latest
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Upgrade pip and install pdm v2+
        run: |
          python -m pip install --upgrade pip
          pip install 'pdm>=2.0.0'

      - name: Install dependencies and develop package
        run: |
          pdm install --no-lock
          pdm develop

      - name: Run main script with arguments
        run: |
          python src/hollywood_pub_sub/main.py --api_key "$TMDB_API_KEY" --max_movies_per_composer 10 --winning_threshold 5
