name: Run Hollywood PubSub Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-main:
    runs-on: ubuntu-latest
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}  # Use your GitHub repo secret here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install pdm
        run: pip install --upgrade pip pdm

      - name: Install dependencies with pdm
        run: pdm install --no-lock

      - name: Install package in editable mode
        run: pdm develop

      - name: Run main script
        run: pdm run python -m hollywood_pub_sub.main --api_key "$TMDB_API_KEY" --max_movies_per_composer 10 --winning_threshold 5
